### PR TITLE
#180: Promised request options

### PR DESCRIPTION
**Pull request by South-Paw**
# Why

Allows promised request options to be provided to components and hooks.

See #180 for more detail

### CODE REVIEW

**Comment by South-Paw** [comment]
@fabien0102 I've just done a first attempt at this... while the relevant tests look green I'm unsure if I've implemented it correctly.

There are a few failing tests to do with `refetch after update` and `with debounce` as well, I can't see why/how these are failing at the moment either

Any more help or guidance would be appreciated 😂

**Comment by fabien0102** [comment]
I don't see any obvious wrong things in your draft ^^ I need to play a bit with your branch to see why it's failing, probably something about timing but not totally sure yet 😕

I will try to give a look later today, but it's the bit the rush over there, so I can't give you any garanties 😬

**Comment by South-Paw** [comment]
Hi @fabien0102 would you or anyone else be able to provide help to get this across the line?

**Comment by South-Paw** [comment]
Since this isn't moving anywhere I've opted to look for other solutions.

**Comment by fabien0102** [comment]
@South-Paw Sorry for the late response, I was totally under-water and I didn't see the notification… I can have a look today 😉

**Comment by South-Paw** [comment]
@fabien0102 that would be epic, sorry to pester you when you're probably busy like me in the lead up to Christmas 😟

I started recreating the hooks/components in a code sandbox this afternoon (after this comment 😄) in an attempt to better understand what's going on under the hood (and with hopes of fixing it for our app) and think I found a few more places where I need to add awaits that seem to make it work as one would expect with awaited requestOptions.

**Comment by fabien0102** [comment]
@South-Paw Don't worry, I know how it can be frustrating to be stuck on a PR because maintainers are busy 😁

**Comment by fabien0102** [comment]
@South-Paw I just fix the first test as example, this should help you to finish, still have a lot to do today, so I let you finish if you have more time than me 😁 (worst case I will try to do this tomorrow "in between" ^^)

=> https://github.com/contiamo/restful-react/tree/promise-request-options (last two commits of the branch)

**Comment by South-Paw** [comment]
@fabien0102 new PR based on your branch 😄 👉 https://github.com/contiamo/restful-react/pull/199

**Pull request closed without merging**
