### PR TITLE
Add fix for #136

### PR DESCRIPTION
**Pull request by AJHenry**
# Why

This PR is to provide a fix for #136 where the fetch request could throw an error after the component was unmounted

## Note

I have not yet been able to create a unit test that consistently reproduces this error as this is a race condition with an error

### CODE REVIEW

**Comment by TejasQ** [comment]
What if we hoist the check for the abort signal above the try/catch block and simply return? It doesn't really make sense to call setState if a request is aborted anyway.

That way we have the check only once.

**Comment by AJHenry** [comment]
I think that would be a better solution, however what if the component unmounts during the fetch request. I am not too familiar with the AbortController but if we passed the abort check, called fetch, then the component unmounted, program execution would continue and we would have to perform the check afterwards anyway?

**Comment by TejasQ** [comment]
[The component cancels on unmount](https://github.com/contiamo/restful-react/blob/529bdb35c9c6baec36cd34ccd76510726b142332/src/Get.tsx#L203) so it can't unmount _during_ the fetch request.

**Comment by AJHenry** [comment]
Right, so when the component will unmount, it will set the abort flag in the AbortController.

So if a user visiting a page with this component on it, the component will mount, and call the fetch request. Now say this fetch request takes 5 seconds to load (because of a slow API), the user can click away from the page, thereby unmounting the component in the middle of the fetch request. 

Now the AbortController will have it's abort flag set and cancel the fetch request, then [the fetch() promise rejects with an AbortError](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) thereby being caught in the try-catch again

**Comment by fabien0102** [comment]
@AJHenry Published on version `8.1.0` 😉

**Pull request merged**
