### PR TITLE
Security audit

### PR DESCRIPTION
**Pull request by stereobooster**
# Why

### CODE REVIEW

**Comment by stereobooster** [comment]
@TejasQ  green.

**Comment by TejasQ** [comment]
Maybe let’s validate this with a canary release and test in the product?

**Comment by stereobooster** [comment]
```
npm build

src/Poll.tsx(343,10): error TS2322: Type '{ requestOptions: {} | {} | { body?: string | Blob | ArrayBufferView | ArrayBuffer | FormData | URLSearchParams | ReadableStream<Uint8Array> | null | undefined; cache?: "default" | ... 5 more ... | undefined; ... 10 more ...; window?: any; } | { ...; } | { ...; } | { ...; }; ... 11 more ...; onError: (err: any, retr...' is not assignable to type 'Partial<Pick<Readonly<PollProps<TData, TError, TQueryParams> & InjectedProps> & Readonly<{ children?: ReactNode; }>, "resolve" | "wait" | "base" | "interval">>'.\n  Types of property 'resolve' are incompatible.\n    Type '((data: any) => any) | ((data: any) => Promise<any>) | ((data: any, prevData: TData | null) => TData)' is not assignable to type '((data: any, prevData: TData | null) => TData) | undefined'.\n      Type '(data: any) => Promise<any>' is not assignable to type '(data: any, prevData: TData | null) => TData'.\n        Type 'Promise<any>' is not assignable to type 'TData'.\n
```

but why our tests doesn't catch it 🤔

**Comment by stereobooster** [comment]
@TejasQ `restful-react@7.2.0-5feeea4` @ canary

**Comment by TejasQ** [comment]
image

image

@stereobooster are you sure about the canary?

**Comment by stereobooster** [comment]
@TejasQ you're right

> You do not have permission to publish "restful-react"

**Comment by TejasQ** [comment]
Fixed. @stereobooster please publish.

**Pull request merged**
