### PR TITLE
feat: sort interfaces by name

### PR DESCRIPTION
**Pull request by vkbansal**
# Why

solves #359

### CODE REVIEW

**Comment by vkbansal** [comment]
@fabien0102 This is how it will work.

Also I would like to do the same here https://github.com/contiamo/restful-react/blob/master/src/scripts/import-open-api.ts#L151

**Comment by fabien0102** [comment]
> @fabien0102 This is how it will work.
> 
> Also I would like to do the same here https://github.com/contiamo/restful-react/blob/master/src/scripts/import-open-api.ts#L151
> 
> Can you suggest a way to do it?

This is indeed quite deep, will be a pain to add an option here… 😕 Otherwise, another approch will be to add a postprocess step, taking the generated file as input, and reordering using typescript compiler directly (https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#re-printing-sections-of-a-typescript-file)

**Comment by fabien0102** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md

Or, you can maybe use an eslint rule (with `--fix`) on this file

**Comment by vkbansal** [comment]
I guess I can also use `transform` options to pre-process the json using [fast-json-stable-stringify](https://www.npmjs.com/package/fast-json-stable-stringify)

**Comment by fabien0102** [comment]
> I guess I can also use `transform` options to pre-process the json using [fast-json-stable-stringify](https://www.npmjs.com/package/fast-json-stable-stringify)

Indeed! Smart idea!

**Pull request closed without merging**
